### PR TITLE
rename error name (fix #5)

### LINKED ISSUE #5: rename PERMISSION_DENIED error
PERMISSION_DENIED error needs to be renamed to PermissionDeniedError (I think)
Version bump.

### PR DESCRIPTION
**Pull request by sualko**
- change PERMISSION_DENIED to NotAllowedError

Should I bump version? If yes, to which number?

fix #5

### CODE REVIEW

**Comment by sualko** [comment]
cc @xdumaine

**Comment by tgabi333** [comment]
i think it's a bc break, so it needs a major bump

**Comment by xdumaine** [comment]
@sualko Please don't change the version number in the PR. We usually do that after merging, before releasing, to avoid conflicts. I agree with @tgabi333 that it's a major version bump.

**Comment by sualko** [comment]
@xdumaine That's the reason why I asked. Great that you merged all of this so fast. Awesome work!

**Comment by xdumaine** [comment]
Published as 2.0.0

**Pull request merged**
