### PR TITLE
Typo constraints for constraint

### PR DESCRIPTION
**Pull request by MichaelJCole**
Hey, I found a typo in this library when I tried to use it outside of SimpleWebRTC.

Thanks!

### CODE REVIEW

**Comment by xdumaine** [comment]
Thanks! LGTM, for future reference, I think the preference is to just update the source file for PRs, and we'll bump version and rebundle after merging, to prevent rebundle conflicts with simultaneous PRs.

**Comment by MichaelJCole** [comment]
Ok, will do.  I didn't know how to rebuild it, so editing the bundled file was the simplest thing that could possibly work.  Thanks!

**Comment by fippo** [comment]
LGTM too. @xdumaine can you merge and npm publish a patch version?

**Comment by xdumaine** [comment]
Done.

**Pull request merged**
